OBJETOS_CELESTES_INICIALES = [
    {
        "nombre": "Sol",
        "tipo_objeto": "estrella",
        "descripcion": "Estrella principal del sistema solar y fuente dominante de energia para la Tierra.",
        "coordenadas": {"ascension_recta": 286.13, "declinacion": 63.87},
        "propiedades_fisicas": {
            "distancia_anios_luz": 0.0000158,
            "masa_tierra": 333000,
            "radio_tierra": 109,
            "temperatura_kelvin": 5778,
        },
        "etiquetas": ["sistema_solar", "estrella_tipo_g"],
    },
    {
        "nombre": "Tierra",
        "tipo_objeto": "planeta",
        "descripcion": "Planeta rocoso del sistema solar con agua liquida estable y vida conocida.",
        "coordenadas": {"ascension_recta": 0.0, "declinacion": 0.0},
        "propiedades_fisicas": {
            "distancia_anios_luz": 0.0,
            "masa_tierra": 1,
            "radio_tierra": 1,
            "temperatura_kelvin": 288,
            "periodo_orbital_dias": 365.25,
            "indice_habitabilidad": 1,
        },
        "etiquetas": ["sistema_solar", "zona_habitable", "vida"],
    },
    {
        "nombre": "Marte",
        "tipo_objeto": "planeta",
        "descripcion": "Planeta rocoso frio con evidencias de agua antigua y alto interes astrobiologico.",
        "coordenadas": {"ascension_recta": 317.68, "declinacion": -23.49},
        "propiedades_fisicas": {
            "distancia_anios_luz": 0.000024,
            "masa_tierra": 0.107,
            "radio_tierra": 0.532,
            "temperatura_kelvin": 210,
            "periodo_orbital_dias": 687,
            "indice_habitabilidad": 0.36,
        },
        "etiquetas": ["sistema_solar", "planeta_rocoso", "astrobiologia"],
    },
    {
        "nombre": "Europa",
        "tipo_objeto": "luna",
        "descripcion": "Luna de Jupiter con superficie helada y posible oceano subsuperficial.",
        "coordenadas": {"ascension_recta": 268.0, "declinacion": -22.0},
        "propiedades_fisicas": {
            "distancia_anios_luz": 0.000063,
            "masa_tierra": 0.008,
            "radio_tierra": 0.245,
            "temperatura_kelvin": 102,
            "indice_habitabilidad": 0.55,
        },
        "etiquetas": ["sistema_solar", "luna", "oceano_subsuperficial"],
    },
    {
        "nombre": "Titan",
        "tipo_objeto": "luna",
        "descripcion": "Luna de Saturno con atmosfera densa y lagos de hidrocarburos en su superficie.",
        "coordenadas": {"ascension_recta": 40.66, "declinacion": 18.46},
        "propiedades_fisicas": {
            "distancia_anios_luz": 0.00014,
            "masa_tierra": 0.0225,
            "radio_tierra": 0.404,
            "temperatura_kelvin": 94,
            "indice_habitabilidad": 0.42,
        },
        "etiquetas": ["sistema_solar", "luna", "atmosfera_densa"],
    },
    {
        "nombre": "Proxima Centauri b",
        "tipo_objeto": "exoplaneta",
        "descripcion": "Exoplaneta cercano que orbita en la zona habitable de Proxima Centauri.",
        "coordenadas": {"ascension_recta": 217.43, "declinacion": -62.68},
        "propiedades_fisicas": {
            "distancia_anios_luz": 4.24,
            "masa_tierra": 1.27,
            "periodo_orbital_dias": 11.2,
            "indice_habitabilidad": 0.68,
        },
        "etiquetas": ["exoplaneta", "zona_habitable", "estrella_enana_roja"],
    },
    {
        "nombre": "Kepler-186f",
        "tipo_objeto": "exoplaneta",
        "descripcion": "Exoplaneta de tamano similar a la Tierra ubicado en la zona habitable de su estrella.",
        "coordenadas": {"ascension_recta": 298.21, "declinacion": 43.96},
        "propiedades_fisicas": {
            "distancia_anios_luz": 492,
            "radio_tierra": 1.17,
            "periodo_orbital_dias": 129.9,
            "indice_habitabilidad": 0.72,
        },
        "etiquetas": ["exoplaneta", "zona_habitable", "kepler"],
    },
    {
        "nombre": "TRAPPIST-1e",
        "tipo_objeto": "exoplaneta",
        "descripcion": "Exoplaneta rocoso del sistema TRAPPIST-1 con condiciones potencialmente compatibles con agua liquida.",
        "coordenadas": {"ascension_recta": 346.62, "declinacion": -5.04},
        "propiedades_fisicas": {
            "distancia_anios_luz": 40.7,
            "masa_tierra": 0.77,
            "radio_tierra": 0.92,
            "periodo_orbital_dias": 6.1,
            "indice_habitabilidad": 0.81,
        },
        "etiquetas": ["exoplaneta", "zona_habitable", "sistema_compacto"],
    },
    {
        "nombre": "Via Lactea",
        "tipo_objeto": "galaxia",
        "descripcion": "Galaxia espiral barrada que contiene el sistema solar y miles de millones de estrellas.",
        "coordenadas": {"ascension_recta": 266.42, "declinacion": -29.01},
        "propiedades_fisicas": {"distancia_anios_luz": 0},
        "etiquetas": ["galaxia", "espiral_barrada"],
    },
    {
        "nombre": "Andromeda",
        "tipo_objeto": "galaxia",
        "descripcion": "Galaxia espiral cercana a la Via Lactea y miembro principal del Grupo Local.",
        "coordenadas": {"ascension_recta": 10.68, "declinacion": 41.27},
        "propiedades_fisicas": {"distancia_anios_luz": 2537000},
        "etiquetas": ["galaxia", "grupo_local", "messier"],
    },
    {
        "nombre": "Nebulosa de Orion",
        "tipo_objeto": "nebulosa",
        "descripcion": "Region de formacion estelar visible en la constelacion de Orion.",
        "coordenadas": {"ascension_recta": 83.82, "declinacion": -5.39},
        "propiedades_fisicas": {"distancia_anios_luz": 1344},
        "etiquetas": ["nebulosa", "formacion_estelar", "messier"],
    },
    {
        "nombre": "Alpha Centauri",
        "tipo_objeto": "sistema_estelar",
        "descripcion": "Sistema estelar triple mas cercano al sistema solar, compuesto por Alpha Centauri A, B y Proxima Centauri.",
        "coordenadas": {"ascension_recta": 219.9, "declinacion": -60.83},
        "propiedades_fisicas": {"distancia_anios_luz": 4.37},
        "etiquetas": ["sistema_estelar", "vecindario_solar"],
    },
]
